# Generated by Django 4.0.4 on 2022-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='hello how are you'),
            preserve_default=False,
        ),
    ]
